### ISSUE TITLE
Tag the latest version

### ISSUE THREAD

**Issue by codeaid** [browscap/browscap-php#242]
Is there a plan to tag the current changes any time soon?

Currently, when using this library with PHP 7.2, `composer` actions require adding the `--ignore-platform-reqs` flag every time you want to install/update/require something.

I see that a fix was committed to `composer.json` file a while ago, however the latest `4.0.0` tag still points 11 commits back from the HEAD.

Thanks!

**Comment by mimmi20** [comment]
@asgrim Could you answer this?

**Comment by asgrim** [comment]
Now that we released Roave/DoctrineSimpleCache with PHP 7.2 support, I think we can tag this :+1:

**Comment by asgrim** [comment]
Release https://github.com/browscap/browscap-php/releases/tag/4.1.0 is now out :+1:  thanks!

**Comment by codeaid** [comment]
Thanks! That fixed it. 

For those still having issues, just doing `composer update browscap/browscap-php` isn't enough. It causes the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/doctrine-simplecache 1.1.0 requires php ~7.1.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - roave/doctrine-simplecache 1.1.0 requires php ~7.1.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - roave/doctrine-simplecache 1.1.0 requires php ~7.1.0 -> your PHP version (7.2.1) does not satisfy that requirement.
    - Installation request for roave/doctrine-simplecache (locked at 1.1.0) -> satisfiable by roave/doctrine-simplecache[1.1.0].
```

The solution to that is to manually force the update of the dependency by running `composer update browscap/browscap-php roave/doctrine-simplecache`. That runs with no issues and updates the Roave library to v2.1.1.
